#!/usr/bin/bash
#"Time-stamp: <11/18/2012  9:30:59 AM rsg>"
#
function makeManPage() {
  pydoc $1.py > $1.man
}

# test_multi_author_copyright
# test_tsCurses
# test_tsDiagnosticCurses
# test_tsParseAcceleratorTextLabel
# test_tsWxAcceleratorEntry
# test_tsWxAUI
# test_tsWxBoxSizer
# test_tsWxCheckBox
# test_tsWxCheckBoxEvent
# test_tsWxCliLinesOfCode
# test_tsWxDiagnostic
# test_tsWxDialogDemo
# test_tsWxDisplay
# test_tsWxEvents
# test_tsWxFieldMarkup
# test_tsWxFileCommander
# test_tsWxFrame
# test_tsWxGauge
# test_tsWxGraphicalTextUserInterface
# test_tsWxGridSizer
# test_tsWxKeyEvents
# test_tsWxLinesOfCode
# test_tsWxLogo
# test_tsWxMarkupDiagnostic
# test_tsWxMetrics
# test_tsWxMidiWindow
# test_tsWxMouseEvent
# test_tsWxOverlays
# test_tsWxPasswordEntryDialog
# test_tsWxPySimpleApp
# test_tsWxRadioBox
# test_tsWxRadioBoxEvent
# test_tsWxRSM
# test_tsWxScrollBar
# test_tsWxScrolled
# test_tsWxScrolled3Boxes
# test_tsWxScrolledWindow
# test_tsWxScrolledWindowDual
# test_tsWxSplashScreen
# test_tsWxStaticBoxSizer
# test_tsWxStaticLine
# test_tsWxStaticText
# test_tsWxStatusBar
# test_tsWxSystemSettings
# test_tsWxTaskBar
# test_tsWxTemplate
# test_tsWxTextCtrl
# test_tsWxTextEntryDialog
# test_tsWxVt100Widgets
# test_tsWxWidgets
# test_tsWxWidgetsMarkup
makeManPage ./configobj
makeManPage ./decorator
makeManPage ./threadpool
makeManPage ./tsApplication
makeManPage ./tsCommandLineInterface
makeManPage ./tsConfig
makeManPage ./tsDecorators
makeManPage ./tsExceptions
makeManPage ./tsGraphicalTextUserInterface
makeManPage ./tsLogger
makeManPage ./tsOptionParser
makeManPage ./tsPlatformRunTimeEnvironment
makeManPage ./tsReAuthor
makeManPage ./tsReportUtilities
makeManPage ./tsReVersion
makeManPage ./tsSysCommands
makeManPage ./tsThreadPool
makeManPage ./tsTreeTrimLines
makeManPage ./tsTreeTrimShutil
makeManPage ./tsWx
makeManPage ./tsWxAcceleratorEntry
makeManPage ./tsWxAcceleratorTable
makeManPage ./tsWxApp
makeManPage ./tsWxBoxSizer
makeManPage ./tsWxButton
makeManPage ./tsWxCallLater
makeManPage ./tsWxCaret
makeManPage ./tsWxCheckBox
makeManPage ./tsWxChoice
makeManPage ./tsWxCliLinesOfCode
makeManPage ./tsWxColor
makeManPage ./tsWxColorDatabase
makeManPage ./tsWxCommandLineEnv
makeManPage ./tsWxControl
makeManPage ./tsWxControlWithItems
makeManPage ./tsWxCursor
makeManPage ./tsWxDebugHandlers
makeManPage ./tsWxDialog
makeManPage ./tsWxDisplay
makeManPage ./tsWxDoubleLinkedList
makeManPage ./tsWxEraseEvent
makeManPage ./tsWxEvent
makeManPage ./tsWxEventDaemon
makeManPage ./tsWxEventLoop
makeManPage ./tsWxEventLoopActivator
makeManPage ./tsWxEventQueueEntry
makeManPage ./tsWxEventTableEntry
makeManPage ./tsWxEvtHandler
makeManPage ./tsWxFlexGridSizer
makeManPage ./tsWxFocusEvent
makeManPage ./tsWxFrame
makeManPage ./tsWxGauge
makeManPage ./tsWxGlobals
makeManPage ./tsWxGraphicalTextUserInterface
makeManPage ./tsWxGridBagSizer
makeManPage ./tsWxGridSizer
makeManPage ./tsWxItemContainer
makeManPage ./tsWxKeyboardState
makeManPage ./tsWxKeyEvent
makeManPage ./tsWxLayout_h
makeManPage ./tsWxLayoutAlgorithm
makeManPage ./tsWxLayoutGTUI
makeManPage ./tsWxLinesOfCode
makeManPage ./tsWxListBox
makeManPage ./tsWxLog
makeManPage ./tsWxMenu
makeManPage ./tsWxMenuBar
makeManPage ./tsWxMouseEvent
makeManPage ./tsWxMouseState
makeManPage ./tsWxMultiFrameEnv
makeManPage ./tsWxNonLinkedList
makeManPage ./tsWxObject
makeManPage ./tsWxPanel
makeManPage ./tsWxPasswordEntryDialog
makeManPage ./tsWxPoint
makeManPage ./tsWxPyApp
makeManPage ./tsWxPyEventBinder
makeManPage ./tsWxPyOnDemandOutputWindow
makeManPage ./tsWxPySimpleApp
makeManPage ./tsWxPySizer
makeManPage ./tsWxRadioBox
makeManPage ./tsWxRadioButton
makeManPage ./tsWxRect
makeManPage ./tsWxReVersion
makeManPage ./tsWxScreen
makeManPage ./tsWxScrollBar
makeManPage ./tsWxScrollBarButton
makeManPage ./tsWxScrollBarGauge
makeManPage ./tsWxScrolled
makeManPage ./tsWxScrolledText
makeManPage ./tsWxScrolledWindow
makeManPage ./tsWxShowEvent
makeManPage ./tsWxSize
makeManPage ./tsWxSizer
makeManPage ./tsWxSizerFlags
makeManPage ./tsWxSizerItem
makeManPage ./tsWxSizerItemList
makeManPage ./tsWxSizerSpacer
makeManPage ./tsWxSlider
makeManPage ./tsWxSplashScreen
makeManPage ./tsWxStaticBox
makeManPage ./tsWxStaticBoxSizer
makeManPage ./tsWxStaticLine
makeManPage ./tsWxStaticText
makeManPage ./tsWxStatusBar
makeManPage ./tsWxSystemSettings
makeManPage ./tsWxTaskBar
makeManPage ./tsWxTextCtrl
makeManPage ./tsWxTextEditBox
makeManPage ./tsWxTextEntry
makeManPage ./tsWxTextEntryDialog
makeManPage ./tsWxTimer
makeManPage ./tsWxToggleButton
makeManPage ./tsWxTopLevelWindow
makeManPage ./tsWxValidator
makeManPage ./tsWxWindow
