#!/bin/bash
#"Time-stamp: <08/25/2016  8:15:45 AM rsg>"
#
# File: run_tsLibCLI_test_script.sh
#
python test_bit_shift.py
python test_nCursesDemo.py
python test_PythonReturnTypes.py
python test_TermsAndConditions.py
python test_tsApplication.py
python test_tsCommandLineEnv.py
python test_tsCommandLineInterface.py
python test_tsCxGlobals.py
python test_tsDoubleLinkedList.py
python test_tsExceptions.py
python test_tsLinesOfCode.py
python test_tsLogger.py
python test_tsOperatorSettingsParser.py
python test_tsPlatformRunTimeEnvironment.py
python test_tsReportUtilities.py
python test_tsStripComments.py
python test_tsStripSettingsParser.py
python test_tsSysCommands.py
python test_tsWxAcceleratorEntry.py
python test_tsWxAUI.py
python test_tsWxBoxLogo.py
python test_tsWxBoxSizer.py
python test_tsWxCheckBox.py
python test_tsWxCheckBoxEvent.py
python test_tsWxCliLinesOfCode.py
python test_tsWxCurses.py
python test_tsWxDiagnostic.py
python test_tsWxDialogDemo.py
python test_tsWxDisplay.py
python test_tsWxDoubleLinkedList.py
python test_tsWxFieldMarkup.py
python test_tsWxFileCommander.py
python test_tsWxFrame.py
python test_tsWxGauge.py
python test_tsWxGlobals.py
python test_tsWxGraphicalTextUserInterface.py
python test_tsWxGridSizer.py
python test_tsWxKeyEvents.py
python test_tsWxLinesOfCode.py
python test_tsWxLogo.py
python test_tsWxMarkupDiagnostic.py
python test_tsWxMetrics.py
python test_tsWxMidiWindow.py
python test_tsWxMouseEvent.py
python test_tsWxMultiFrameEnv.py
python test_tsWxOverlays.py
python test_tsWxPasswordEntryDialog.py
python test_tsWxPySimpleApp.py
python test_tsWxRadioBox.py
python test_tsWxRadioBoxEvent.py
python test_tsWxRSM.py
python test_tsWxScrollBar.py
python test_tsWxScrolled.py
python test_tsWxScrolled3Boxes.py
python test_tsWxScrolledWindow.py
python test_tsWxScrolledWindowDual.py
python test_tsWxSplashScreen.py
python test_tsWxStaticBoxSizer.py
python test_tsWxStaticLine.py
python test_tsWxStaticText.py
python test_tsWxSystemSettings.py
python test_tsWxTemplate.py
python test_tsWxTextCtrl.py
python test_tsWxTextEntryDialog.py
python test_tsWxVt100Widgets.py
python test_tsWxWidgets.py
python test_tsWxWidgetsMarkup.py
python tsApplication.py
python tsCommandLineEnv.py
python tsCommandLineInterface.py
python tsConfig.py
python tsCxGlobals.py
python tsDoubleLinkedList.py
python tsExceptions.py
python tsGistGetTerminalSize.py
python tsLinesOfCode.py
python tsLinesOfCodeProjectMetrics.py
python tsLOCPMOperatorSettingsParser.py
python tsLogger.py
python tsOperatorSettingsParser.py
python tsOperatorSettingsParserBuilder.py
python tsPlatformQuery.py
python tsPlatformRunTimeEnvironment.py
python tsProjectMetrics.py
python tsReportUtilities.py
python tsSoftwareMetrics.py
python tsSoftwareParser.py
python tsStripComments.py
python tsStripLineNumbers.py
python tsStripSettingsParser.py
python tsSysCommands.py
python tsTreeCopy.py
python tsTreeTrimLines.py
python tsTreeTrimShutil.py
python tsWx.py
python tsWxAcceleratorEntry.py
python tsWxAcceleratorTable.py
python tsWxApp.py
python tsWxBoxSizer.py
python tsWxButton.py
python tsWxCallLater.py
python tsWxCaret.py
python tsWxCheckBox.py
python tsWxChoice.py
python tsWxColor.py
python tsWxColorDatabase.py
python tsWxControl.py
python tsWxControlWithItems.py
python tsWxCursor.py
python tsWxDebugHandlers.py
python tsWxDialog.py
python tsWxDialogButton.py
python tsWxDisplay.py
python tsWxDoubleLinkedList.py
python tsWxEraseEvent.py
python tsWxEvent.py
python tsWxEventDaemon.py
python tsWxEventLoop.py
python tsWxEventLoopActivator.py
python tsWxEventQueueEntry.py
python tsWxEventTableEntry.py
python tsWxEvtHandler.py
python tsWxFlexGridSizer.py
python tsWxFocusEvent.py
python tsWxFrame.py
python tsWxFrameButton.py
python tsWxGauge.py
python tsWxGlobals.py
python tsWxGraphicalTextUserInterface.py
python tsWxGridBagSizer.py
python tsWxGridSizer.py
python tsWxItemContainer.py
python tsWxKeyboardState.py
python tsWxKeyEvent.py
python tsWxListBox.py
python tsWxLog.py
python tsWxMenu.py
python tsWxMenuBar.py
python tsWxMouseEvent.py
python tsWxMouseState.py
python tsWxMultiFrameEnv.py
python tsWxNonLinkedList.py
python tsWxObject.py
python tsWxPanel.py
python tsWxPasswordEntryDialog.py
python tsWxPoint.py
python tsWxPyApp.py
python tsWxPyEventBinder.py
python tsWxPyOnDemandOutputWindow.py
python tsWxPySimpleApp.py
python tsWxPySizer.py
python tsWxPythonColor16DataBase.py
python tsWxPythonColor16SubstitutionMap.py
python tsWxPythonColor256DataBase.py
python tsWxPythonColor88DataBase.py
python tsWxPythonColor8DataBase.py
python tsWxPythonColor8SubstitutionMap.py
python tsWxPythonColorDataBaseRGB.py
python tsWxPythonColorNames.py
python tsWxPythonColorRGBNames.py
python tsWxPythonColorRGBValues.py
python tsWxPythonMonochromeDataBase.py
python tsWxPythonPrivateLogger.py
python tsWxRadioBox.py
python tsWxRadioButton.py
python tsWxRect.py
python tsWxScreen.py
python tsWxScrollBar.py
python tsWxScrollBarButton.py
python tsWxScrollBarGauge.py
python tsWxScrolled.py
python tsWxScrolledText.py
python tsWxScrolledWindow.py
python tsWxShowEvent.py
python tsWxSize.py
python tsWxSizer.py
python tsWxSizerFlags.py
python tsWxSizerItem.py
python tsWxSizerItemList.py
python tsWxSizerSpacer.py
python tsWxSlider.py
python tsWxSplashScreen.py
python tsWxStaticBox.py
python tsWxStaticBoxSizer.py
python tsWxStaticLine.py
python tsWxStaticText.py
python tsWxStatusBar.py
python tsWxSystemSettings.py
python tsWxTaskBar.py
python tsWxTextCtrl.py
python tsWxTextEditBox.py
python tsWxTextEntry.py
python tsWxTextEntryDialog.py
python tsWxTimer.py
python tsWxToggleButton.py
python tsWxTopLevelWindow.py
python tsWxValidator.py
python tsWxWindow.py
python tsWxWindowCurses.py
